apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: auth-service
  template:
    metadata:
      name: auth-service
      labels:
        name: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    name: auth-service
  ports:
    - port: 3000
      targetPort: 3000
